import Head from "next/head";
import ReturnPolicy from "../../components/__pages/return-policy/ReturnPolicy";

export default function ReturnPolicyPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ReturnPolicy />
    </>
  );
}
