import Head from "next/head";
import Cart from "../../components/__pages/cart/Cart";

export default function ProductsPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cart />
    </>
  );
}
