import Head from "next/head";
import PaymentOptions from "../../components/__pages/payment-options/PaymentOptions";
import { GetServerSideProps } from "next";
export default function PaymentMethodPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaymentOptions />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const referrer = await Promise.resolve(context.req.headers.referer || "/");

  if (!referrer.endsWith("/checkout")) {
    return {
      redirect: {
        destination: "/checkout",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
