import Head from "next/head";
import Signin from "../../components/__pages/signin/Signin";
import { GetServerSideProps } from "next";
import { fetchCall } from "../../lib/contentful/contentful";

export default function SigninPage({ b }: { b: unknown }) {
  console.log(b);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signin />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const b = await fetchCall(
    `
  query {
    productCollection {
      items {
        id
        name
        sizes
        tag
        price
        description
        imagesCollection {
          items {
            url
          }
        }
      }
    }
  } 
  `
  );
  return {
    props: {
      b,
    },
  };
};
