import Head from "next/head";
import Account from "../../components/__pages/account/Account";

export default function AccountPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Account />
    </>
  );
}
